name: Run Script Daily

on:
  schedule:
    - cron: '1 0 * * *'  # Runs every day at 12:01 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debugging: Print Secrets (For Debugging Only!)
        run: |
          echo "TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}"
          echo "TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}"
          echo "TOMORROW_API_KEY: ${{ secrets.TOMORROW_API_KEY }}"

      - name: Run Python script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TOMORROW_API_KEY: ${{ secrets.TOMORROW_API_KEY }}
        run: |
          python main.py
