name: Run Script Daily

on:
  # Automatically runs the workflow at 12:01 AM UTC (5:01 AM BDT)
  schedule:
    - cron: '1 0 * * *'  # Runs every day at 12:01 AM UTC (5:01 AM BDT)
  
  # Allows manual triggering of the workflow from the GitHub UI
  workflow_dispatch:  # This will allow you to manually trigger the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest
    environment: Rainmeter  # Specify the environment here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TOMORROW_API_KEY: ${{ secrets.TOMORROW_API_KEY }}
        run: |
          python main.py
